apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ include "go-btfs.name" . }}
    chart: {{ include "go-btfs.chart" . }}
    component: "{{ .Values.name }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ include "go-btfs.fullname" . }}
data:
{{ toYaml .Values.extraData | indent 2 }}
