apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "go-btfs.fullname" . }}
  labels:
    app: {{ include "go-btfs.name" . }}
    chart: {{ include "go-btfs.chart" . }}
    component: "{{ .Values.name }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "go-btfs.name" . }}
      component: "{{ .Values.name }}"
      release: {{ .Release.Name }}
  strategy:
    rollingUpdate: 
      maxSurge: {{ .Values.maxSurge }}
      maxUnavailable: {{ .Values.maxUnavailable }}
    type: {{ .Values.strategyType }}
  template:
    metadata:
      labels:
        app: {{ include "go-btfs.name" . }}
        component: "{{ .Values.name }}"
        release: {{ .Release.Name }}
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
        checksum/config: {{ include (print .Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print .Template.BasePath "/secret.yaml") . | sha256sum }}
      {{- range $key, $value := .Values.deploymentAnnotations }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
    spec:
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      containers:
        - name: {{ include "go-btfs.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          resources:
{{ toYaml .Values.resources | indent 12 }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.readiness.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readiness.path }}
              port: {{ .Values.readiness.port }}
            initialDelaySeconds: {{ .Values.readiness.delay }}
            periodSeconds: {{ .Values.readiness.period }}
            timeoutSeconds: {{ .Values.readiness.timeoutSeconds }}
          {{- end }}
          {{- if .Values.liveness.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.liveness.path }}
              port: {{ .Values.liveness.port }}
            initialDelaySeconds: {{ .Values.liveness.delay }}
            periodSeconds: {{ .Values.liveness.period }}
            timeoutSeconds: {{ .Values.liveness.timeoutSeconds }}
          {{- end }}
          {{- if .Values.ports }}
          ports:
            {{- range $key, $value := .Values.ports }}
            - name: {{ $value.name }}
              containerPort: {{ $value.containerPort }}
              protocol: {{ $value.protocol }}
            {{- end }}
          {{- end }}
          {{- if .Values.containerArgs }}
          args: {{ .Values.containerArgs }}
          {{- end }}
          env:
            {{- range $key, $value := .Values.extraEnv }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
            {{- range $key, $_ := $.Values.goBtfsSecrets }}
            - name: {{ $key | upper }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "go-btfs.fullname" $ }}
                  key: {{ $key }}
            {{- end }}
          envFrom:
          - configMapRef:
              name: {{ include "go-btfs.fullname" . }}
              {{- if .Values.volumeMounts }}
          volumeMounts:
          {{- range .Values.volumeMounts }}
          - name: {{ .name }}
            mountPath: {{ .mountPath | quote }}
            readOnly: {{ .readOnly }}
          {{- end }}
          {{- end }}
    {{- with .Values.volumes }}
      volumes:
{{ toYaml . | indent 6 }}
    {{- end }}