apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  annotations:
    kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/scheme: {{ .Values.ingress.alb.scheme }}
    alb.ingress.kubernetes.io/target-type: {{ .Values.ingress.alb.targetType }}
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.ingress.alb.certificateArn }}
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '15'
    alb.ingress.kubernetes.io/load-balancer-attributes: {{ .Values.ingress.alb.attributes }}
    alb.ingress.kubernetes.io/web-acl-id: {{ .Values.ingress.alb.webAclId }}
    alb.ingress.kubernetes.io/inbound-cidrs: {{ .Values.ingress.alb.inboundCidrs }}
    alb.ingress.kubernetes.io/healthcheck-path: {{ .Values.ingress.alb.healthcheckPath }}
    alb.ingress.kubernetes.io/healthcheck-port: {{ .Values.ingress.alb.healthcheckPort }}
spec:
{{/*  tls:*/}}
{{/*    - hosts:*/}}
{{/*        {{- range $key, $value := .Values.ingress.domains }}*/}}
{{/*        - {{ $value.name }}*/}}
{{/*      {{- end }}*/}}
{{/*      secretName: {{ $.Values.ingress.secretName }}*/}}
  rules:
    {{- $dot := . }}
    {{- range $key, $value := .Values.ingress.domains }}
    - host: {{ $value.name }}
      http:
        paths:
          - path: {{ $value.path }}
            backend:
              serviceName: {{ template "go-btfs.fullname" $dot }}
              servicePort: api
    {{- end }}
{{/*    - host: btfs.{{ required "A valid .Values.albExternal.domain entry requried!" .Values.albExternal.domain }}*/}}
{{/*      http:*/}}
{{/*        paths:*/}}
{{/*        - path: /**/}}
{{/*          backend:*/}}
{{/*            serviceName: {{ include "linoapp.btfs.fullname" . }}*/}}
{{/*            servicePort: api*/}}