apiVersion: v1
kind: Service
metadata:
  name: {{ include "go-btfs.fullname" . }}
  labels:
    app: {{ include "go-btfs.name" . }}
    chart: {{ include "go-btfs.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
  {{- range $key, $value := .Values.serviceAnnotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8082
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: 4012
      targetPort: http
      protocol: TCP
      name: http

  selector:
    app: {{ include "go-btfs.name" . }}
    component: "{{ .Values.name }}"
    release: {{ .Release.Name }}
