apiVersion: v1
kind: Service
metadata:
  name: {{ include "go-btfs.fullname" . }}
  labels:
    app: {{ include "go-btfs.name" . }}
    chart: {{ include "go-btfs.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
  {{- range $key, $value := .Values.serviceAnnotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: gateway
    - port: 5001
      targetPort: 5001
      protocol: TCP
      name: api
    - port: 4001
      targetPort: 4001
      protocol: TCP
      name: swarm
    - port: 5101
      targetPort: 5101
      protocol: TCP
      name: remote-api

  selector:
    app: {{ include "go-btfs.name" . }}
    component: "{{ .Values.name }}"
    release: {{ .Release.Name }}
