apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.persistent.storageClassName }}
parameters:
  fsType: ext4
  type: sc1
provisioner: kubernetes.io/aws-ebs
allowVolumeExpansion: true
reclaimPolicy: Delete