name: go-btfs
nameOverride: ""
fullnameOverride: ""
service:
  type: ClusterIP
  port: 80
virtualservice:
  attempts: 3
  perTryTimeout: 10s
resources:
  limits:
    cpu: 2000m
    memory: 2000Mi
  requests:
    cpu: 1000m
    memory: 1000Mi
extraEnv: {}
extraData: {}
serviceAnnotations: {}
deploymentAnnotations: {}
readiness:
  # Readiness prob is highly recommended
  enabled: true
  path: /
  port: 4001
  delay: 0
  period: 10
  timeoutSeconds: 5
liveness:
  # Liveness prob is highly recommended
  enabled: true
  path: /
  port: 4001
  delay: 300
  period: 10
  timeoutSeconds: 5
nodeSelector: {}
tolerations: []
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: component
            operator: In
            values: 
            - "go-btfs"
        topologyKey: kubernetes.io/hostname
ports:
  # Any ports that you are exposed for other service, or health check purpose
- name: tcp
  containerPort: 4001
  protocol: TCP
- name: daemon
  containerPort: 5001
  protocol: TCP
- name: web
  containerPort: 8080
  protocol: TCP
- name: socket
  containerPort: 8081
  protocol: TCP

replicaCount: 1
maxSurge: 1
maxUnavailable: 0
strategyType: RollingUpdate
image:
  repository: "726332586568.dkr.ecr.eu-west-1.amazonaws.com/go-btfs"
  tag: ""
  pullPolicy: IfNotPresent
autoscaler:
  minReplicas: 1
  maxReplicas: 2
  resourceName: cpu
  targetAverageUtilization: 65
  targetAverageMemoryUtilization: 80
volumeMounts: {}
volumes: {}
containerArgs: []
